app/models/review.rb
app/models/shelter.rb
app/views/shelters/show.html.erb
db/migrate/20191203200450_create_reviews.rb
db/migrate/20191203201130_add_shelter_to_reviews.rb
db/schema.rb
db/seeds.rb
spec/features/shelters/show_spec.rb
spec/models/review_spec.rb
spec/models/shelter_spec.rb

Database
* Add reviews table
* Add shelter id as foreign key on reviews table
* Migrate both migrations into database
Models
* Add test for Review required fields (title, rating, content)
* Create Review model with validations and belongs_to association with shelter
* Add has_many reviews association to Shelter model
Features
* Add feature test to display list of reviews on shelter show page
* Add a reviews section to shelter show page to display reviews for that shelter
* Add reviews to seeds file
All tests passing.

Shelter reviews

---

app/controllers/reviews_controller.rb
app/views/reviews/new.html.erb
app/views/shelters/show.html.erb
config/routes.rb
spec/features/reviews/new_spec.rb

* Add feature test for shelter review creation
* Add link on shelter show page to add a review for that shelter
* Add form to create a new review
* Add routes for new review form and review creation
* Add ReviewsController with new and create methods

Shelter review creation

---

app/controllers/reviews_controller.rb
app/views/reviews/edit.html.erb
app/views/shelters/show.html.erb
config/routes.rb
spec/features/reviews/edit_spec.rb

Fixed the routing bug that was causing it to not find review  ID's.

Shelter review edit

---

app/controllers/application_controller.rb
app/controllers/favorites_controller.rb
app/models/favorite.rb
app/views/layouts/application.html.erb
app/views/pets/show.html.erb
config/routes.rb
db/seeds.rb
spec/features/favorites/add_spec.rb
spec/features/navigation_spec.rb
spec/models/favorite_spec.rb

Features
* Add test that a favorites indicator appears in nav bar on all pages
* Add favorites indicator to nav bar that displays total count of pets in favorites and increments when a pet is added to favorites
* Add FavoritesController with update method
* Add route to update favorites list/add pet to favorites
Models
* Add test for total_count, add_pet, and count_of methods
*  Add Favorite class with total_count, add_pet, and count_of methods
Misc
* Add favorites helper method to ApplicationController to be accessed from all controllers
* Change images for some pets in seeds

Favorite indicator favorite creation

---

Gemfile.lock
app/controllers/favorites_controller.rb
app/models/favorite.rb
app/views/favorites/index.html.erb
config/routes.rb
spec/features/favorites/index_spec.rb
spec/models/favorite_spec.rb

* Make changes to store favorites as array instead of hash
* Add tests and functionality that favorites indicator appears on navigation bar on all pages
* Add tests and functionality that navigation bar increments when pet is added to favorites
* Add tests and functionality that favorited pets appear on the favorites index along with their name and image

Favorites index

---

app/views/layouts/application.html.erb
spec/features/favorites/index_spec.rb
spec/features/navigation_spec.rb

Added testing for the favorites link 
Added link_to Favorites in the navbar
Testing is passing with 100% coverage

Favorites indicator link

---

app/controllers/favorites_controller.rb
app/models/favorite.rb
app/views/pets/show.html.erb
config/routes.rb
spec/features/favorites/destroy_spec.rb
spec/features/favorites/index_spec.rb
spec/models/favorite_spec.rb

* Add test for model method that checks if a pet is included in favorites
* Add model method .included_in_favorites?(pet_id)
* Add feature test for delete pet button on pet show page
* Add route to delete pet from pet show page
* Add conditional statement to view to prevent user from favoriting a pet more than once
* Add destroy method to FavoritesController

Cant favorite more than once

---

app/controllers/favorites_controller.rb
app/views/favorites/index.html.erb
spec/features/favorites/index_spec.rb

* Add feature test that there is a button next to each favorited pet to delete that pet from the favorites index page
* Add delete button next to each pet in the favorites index
* Link each pet's name in the favorites index page to that pet's show page
* Add conditional to destroy method in FavoritesController to redirect depending on previous page

Remove a favorite from favorites page

---

app/views/favorites/index.html.erb
spec/features/favorites/index_spec.rb

* Add feature test that there is a no favorited pets message when favorites index is empty
* Add conditional statement to favorites index to display message when no pets have been favorited

No favorites page

---

app/controllers/favorites_controller.rb
app/views/favorites/index.html.erb
config/routes.rb
spec/features/favorites/index_spec.rb

* Add feature test that there is a link to remove all favorited pets on the favorites index page
* Add link on favorites index page to remove all favorited pets
* Add route to empty favorites list
* Add empty method to FavoritesController

Remove all favorites from favorites page

---

app/models/application.rb
app/models/application_pet.rb
app/models/pet.rb
db/migrate/20191208214419_create_applications.rb
db/migrate/20191208214925_create_application_pets.rb
db/schema.rb
spec/models/application_pet_spec.rb
spec/models/application_spec.rb
spec/models/pet_spec.rb

Paired with Rachel to work on user story 16. Adding pet applications.

Pet application form p

---

app/controllers/applications_controller.rb
app/controllers/favorites_controller.rb
app/models/favorite.rb
app/views/applications/new.html.erb
app/views/favorites/index.html.erb
config/routes.rb
db/migrate/20191209013500_change_phone_number_to_be_bigint_in_applications.rb
db/schema.rb
spec/features/applications/new_spec.rb
spec/models/favorite_spec.rb

* Added feature test for new application form
* Added routes for for the new application form and to create an application
* Added new and create methods to ApplicationsController
* Created view for pet application form
* Added and refactored create method for applications
* Added model test to remove a pet from favorites
* Add model method within Favorite model to remove a pet from favorites by id
* Change check_box_tag

Applying for a pet

---

app/controllers/applications_controller.rb
spec/features/applications/new_spec.rb

* Removed comments from the test that were accidentally left in.
* Added test for verifying all fields on application are filled in.
* Refactored the create method to add flash messages.

Incomplete application

---

app/controllers/favorites_controller.rb
app/views/favorites/index.html.erb
spec/features/applications/new_spec.rb
spec/features/favorites/index_spec.rb

* Added a test for the favorites index page to display pets that have been applied for.
* Added view to display pets applied for.
* Added instance variable pets_applied_for to return all of the pets with applications.
* Updated the applications/new_spec to reflect the added functionality.

Pet applications in favorites

---

app/controllers/applications_controller.rb
app/views/applications/show.html.erb
config/routes.rb
spec/features/applications/show_spec.rb
spec/models/application_spec.rb

* Added zip validation to the application model.
* Created test for application view.
* Added route for application show page.
* Added show method into ApplicationsController.
* Created show view for applications.
* Added @application_details into show method.

Application show page

---

app/controllers/pet_applications_controller.rb
app/views/pet_applications/index.html.erb
app/views/pets/show.html.erb
config/routes.rb
spec/features/applications/pet_applications_index_spec.rb

* Add feature test that pet applications index page lists and links to each applicant if there are applications for that pet or displays a message saying there are no applications for this pet if no one has applied for that pet
* Add link to pet's show page to view all applications for that pet
* Add route for pet applications index
* Add view for pet applications index
* Add PetApplicationsController with index method

Pet applications index

---

app/controllers/shelters_controller.rb
spec/features/shelters/new_spec.rb

* Added testing for flash messages for the shelter create method.
* Added flash messages to the shelter create method.

Shelter flash messages

---

spec/features/shelters/destroy_spec.rb

Tested the review was added and then reduced from Review.count

Added test to verify reviews are being deleted with shelter.Testing 100%

---

app/controllers/shelters_controller.rb
app/models/shelter.rb
app/views/shelters/show.html.erb
spec/features/shelters/edit_spec.rb
spec/features/shelters/show_spec.rb
spec/models/shelter_spec.rb

* Added flash messages for editing shelter without filling in all fields
* Added conditional statement to update method to display flash message and redirect to form when field(s) are left blank
* Added tests for average_rating and application_count methods
* Added average_rating and application_count instance methods to Shelter model
* Added feature test for shelter statistics
* Add shelter statistics section to shelter show page

User stories 29 & 30

---

app/models/pet.rb
app/views/pets/show.html.erb
db/seeds.rb
spec/features/applications/approve_application_spec.rb

Applicant Name Links to Application Show Page

Applicant Name Links to Application Show Page

---

app/controllers/pets_controller.rb
spec/features/pets/edit_spec.rb
spec/features/pets/new_spec.rb

* Added testing for flash messages in editing a pet
* Added flash messages into the PetsController's Create and Update methods
* Testing is passing at 100% coverage
* User Story 33, Flash Message for Pet Create and Update - COMPLETE

Pet create edit flash message

---

app/controllers/applications_controller.rb
app/views/applications/show.html.erb
config/routes.rb
spec/features/applications/approve_application_spec.rb
spec/models/pet_spec.rb

* Add feature test that approved application can be unapproved with an unapprove button that revokes it
* Add conditional statement to view to have an unapprove button when an application is approved
* Add route to revoke an application
* Add conditional to update status method in ApplicationsController
* Add model test for applicant_id method

Approved applications can be revoked

---

app/models/shelter.rb
app/views/shelters/index.html.erb
app/views/shelters/show.html.erb
spec/features/shelters/destroy_spec.rb
spec/models/shelter_spec.rb

* Add model test for any_pending_pets_method
* Add any_pending_pets instance method
* Add conditional statements so links to delete shelter don't show up when that shelter has pending pets

Shelters with pending status pets cannot be deleted

---

spec/features/applications/approve_application_spec.rb
spec/features/applications/new_spec.rb
spec/features/applications/pet_applications_index_spec.rb
spec/features/favorites/index_spec.rb
spec/features/pets/destroy_spec.rb
spec/features/pets/edit_spec.rb
spec/features/pets/new_spec.rb

Refactored all tests to include before each setup blocks and cut out repeated code

Refactored all tests to abide by DRY

---

app/controllers/pets_controller.rb
spec/features/pets/destroy_spec.rb

* Add feature test that deleting a pet also removes that pet from favorites
* Refactor destroy method so deleting a pet also removes it from favorites

Deleting a pet removes it from favorites
